# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hashtag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuari', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('contrasenya', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Missatges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Login')),
            ],
        ),
        migrations.AddField(
            model_name='hashtags',
            name='missatge',
            field=models.ManyToManyField(to='forum.Missatges'),
        ),
    ]
